[package]
name = "dfnhack7_common"
version = "0.1.0"
authors = ["John Plevyak <jplevyak@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ic-cdk = "0.2.4"
serde = "1"
serde_bytes = "0.11"
serde_cbor = "0.11"
